version = 3.8.6
runner.dialect = scala3

project.includeFilters = [
  ".*\\.scala$"
]

maxColumn = 120
indent.main = 2
indent.callSite = 2
indent.defnSite = 2

literals.long = Upper
literals.hexDigits = Upper

docstrings.style = SpaceAsterisk
docstrings.blankFirstLine = true
docstrings.wrap = false

align.preset = more
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses.preset = true

spaces.inImportCurlyBraces = true

newlines.topLevelStatementBlankLines = [
  { blanks { before = 1 } }
]
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.afterCurlyLambda = preserve
newlines.implicitParamListModifierPrefer = before

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors,
]

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
